# Replace <YOUR-TUNNEL-ID>, <DOMAIN>, and <LOCAL-IP> before launching cloudflared container

tunnel: <TUNNEL_ID>
credentials-file: /etc/cloudflared/<TUNNEL_ID>.json

ingress:
  # Radarr (through Gluetun port 7878)
  - hostname: radarr.<DOMAIN>
    service: http://<LOCAL-IP>:7878

  # Sonarr (through Gluetun port 8989)
  - hostname: sonarr.<DOMAIN>
    service: http://<LOCAL-IP>:8989

  # Jellyfin (direct, it has its own network)
  - hostname: jellyfin.<DOMAIN>
    service: http://jellyfin:8096

  # Default catch-all
  - service: http_status:404