# Replace <YOUR-TUNNEL-ID> and "example.com" before launching cloudflared container

tunnel: <YOUR_TUNNEL_ID>
credentials-file: /etc/cloudflared/<YOUR_TUNNEL_ID>.json

ingress:
  # Radarr (through Gluetun port 7878)
  - hostname: radarr.example.com
    service: http://gluetun:7878

  # Sonarr (through Gluetun port 8989)
  - hostname: sonarr.example.com
    service: http://gluetun:8989

  # Jellyfin (direct, it has its own network)
  - hostname: jellyfin.example.com
    service: http://jellyfin:8096

  # Default catch-all
  - service: http_status:404