services:
  gluetun:
    image: qmcgaw/gluetun:v3.39.1
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 9696:9696 # prowlarr
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 8090:8090 # qbittorrent
      - 8191:8191 # flaresolverr
    volumes:
      - ./config/gluetun:/gluetun
    restart: unless-stopped
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      # Timezone for accurate log times
      - TZ=America/Louisville
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
      - SERVER_COUNTRIES=United States
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.27.0
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - TZ=America/Louisville
      - PUID=0
      - PGID=0
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped
  radarr:
    restart: unless-stopped
    container_name: radarr
    network_mode: "service:gluetun"
    volumes:
      - ./config/radarr:/config
      - ./movies:/movies
      - ./downloads:/downloads
    environment:
      - TZ=America/Louisville
      - PUID=0
      - PGID=0
    image: lscr.io/linuxserver/radarr:5.15.1
  sonarr:
    restart: unless-stopped
    container_name: sonarr
    network_mode: "service:gluetun"
    volumes:
      - ./config/sonarr:/config
      - ./tv:/tv
      - ./downloads:/downloads
    environment:
      - TZ=America/Louisville
      - PUID=0
      - PGID=0
    image: lscr.io/linuxserver/sonarr:4.0.11
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.0.2
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - TZ=America/Louisville
      - WEBUI_PORT=8090
      - PUID=0
      - PGID=0
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads # optional
    restart: unless-stopped
    depends_on:
      - gluetun
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.3
    container_name: jellyfin
    environment:
      - TZ=America/Louisville
      - PUID=0
      - PGID=0
      - UMASK_SET=022 # optional
    volumes:
      - ./config/jellyfin:/config
      - ./tv:/data/tvshows:ro
      - ./movies:/data/movies:ro
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr:v3.3.21
    network_mode: "service:gluetun"
    container_name: flaresolverr
    environment:
      - TZ=America/Louisville
    restart: unless-stopped
  npm:
    image: jc21/nginx-proxy-manager:2.10.4
    container_name: npm
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '8001:80' # Public HTTP Port
      - '4431:443' # Public HTTPS Port
      - '8083:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      - TZ=America/Louisville
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./config/npm:/data
      - ./config/letsencrypt:/etc/letsencrypt
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9444:9443
    volumes:
      - ./config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped