networks:
  homelab:
    driver: bridge
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 9696:9696 # prowlarr
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 8090:8090 # qbittorrent web UI
      - 8191:8191 # flaresolverr
    volumes:
      - ./config/gluetun:/gluetun
    restart: unless-stopped
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      # options are wireguard or openvpn
      - VPN_TYPE=wireguard
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Timezone for accurate log times
      - TZ=America/Louisville
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
      - SERVER_COUNTRIES=United States
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - TZ=America/Louisville
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped
    depends_on:
      - gluetun
  radarr:
    restart: unless-stopped
    container_name: radarr
    network_mode: "service:gluetun"
    volumes:
      - ./config/radarr:/config
      - ./data:/data
    environment:
      - TZ=America/Louisville
      - PUID=${PUID}
      - PGID=${PGID}
    image: lscr.io/linuxserver/radarr:latest
    depends_on:
      - gluetun
  sonarr:
    restart: unless-stopped
    container_name: sonarr
    network_mode: "service:gluetun"
    volumes:
      - ./config/sonarr:/config
      - ./data:/data
    environment:
      - TZ=America/Louisville
      - PUID=${PUID}
      - PGID=${PGID}
    image: lscr.io/linuxserver/sonarr:latest
    depends_on:
      - gluetun
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - TZ=America/Louisville
      - WEBUI_PORT=8090
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./config/qbittorrent:/config
      - ./data/torrents:/data/torrents
    restart: unless-stopped
    depends_on:
      - gluetun
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - homelab
    environment:
      - TZ=America/Louisville
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=022 # optional
    volumes:
      - ./config/jellyfin:/config
      - ./data/media:/data/media
    ports:
      - 8096:8096
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    network_mode: "service:gluetun"
    container_name: flaresolverr
    environment:
      - TZ=America/Louisville
    restart: unless-stopped
    depends_on:
      - gluetun
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    networks:
      - homelab
    ports:
      - 9444:9443
    volumes:
      - ./config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ./config/cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - ./config/cloudflared/${TUNNEL_ID}.json:/etc/cloudflared/${TUNNEL_ID}.json:ro
    command: tunnel --no-autoupdate run
